FROM php:7.1-fpm

RUN docker-php-ext-install pdo_mysql

# RUN apt-get update && apt-get install -y libmcrypt-dev \
#     mysql-client libmagickwand-dev --no-install-recommends \
#     && pecl install imagick \
#     && docker-php-ext-enable imagick \
#     && docker-php-ext-install mcrypt pdo_mysql

# RUN apt-get update && \
#     apt-get -y install sudo

# RUN apt-get install -y gnupg


# RUN apt-get install --yes curl
# RUN curl -sL https://deb.nodesource.com/setup_10.x | sudo bash -
# RUN apt-get install --yes nodejs
# RUN apt-get install --yes build-essential

 